### ISSUE TITLE
attachment究竟该翻成什么？

### ISSUE THREAD

**Issue by tumluliu** [tumluliu/carto_zh-cn#1]
attachment是CartoCSS中很有特色的一个概念，也是区别于CSS的特征之一。关于attachment的解释，在[这里](http://www.macwright.org/2012/11/02/css-for-maps.html)，[这里](http://www.developmentseed.org/blog/2011/feb/09/introducing-carto-css-map-styling-language/)和[这里](https://github.com/mapbox/carto/blob/master/README.md)三个地方都有提到。在我的翻译所选择的文档中第一次出现是在[Styling Lines](https://www.mapbox.com/mapbox-studio/styling-lines/)中。但由于我最早选择的CartoCSS基本概念是从[这个页面](https://www.mapbox.com/tilemill/docs/manual/carto/)翻译过来的。而这里面把attachment所指的概念和特征却称为Multiple symbolizers/new symbolizer，通篇都没有提attachment一个字。这就导致了我在后面第一次遇到attachment的时候不知道到底是创造一个新词来对应，还是继续使用之前为new symbolizer准备的“新符号”这个我也觉得很low的译法，目前我暂时使用的是“新符号”。但问题来了，在翻到[Symbol Drawing Order](https://www.mapbox.com/mapbox-studio/symbol-drawing-order/)中的Symbolizer Ordering的时候，第一句话就是Each object in each attachment may have multiple symbolizers applied to it. 我擦，这可怎么办？attachment和multiple symbolizers都出现了。。。

这使我陷入了深深的沉思。

attachment从字面翻译非常简单，就是“附件”，例如email的attachment。但放在地图样式中，结合上下文，再考虑到attachment之于CartoCSS的重要性，实在让我难以接受“附件”这个名字。到底翻成什么才能更精确的反映原文所要表达的意思呢？

**Comment by yarray** [comment]
感觉“（从）属”这个定语比较好，似乎可以考虑“属样式”或“从样式”这种说法，但是看了链接里的资料总觉得Mapbox自己对这个概念也没有非常明晰的定义，很难说“属”什么才是合理的

**Comment by tumluliu** [comment]
我原来考虑过“子样式”这个名字，类似“子程序”、“子过程”之类的概念，但似乎又不太准确。

对了，还有个地方提到了attachment，就是[Symbol Drawing Order](https://www.mapbox.com/mapbox-studio/symbol-drawing-order/)里面，专门有一节是Attachment Ordering，里面的描述还清楚一些。

要不就叫“从属样式”吧，既有“附加的”（attached）的含义，也有一点派生出的子样式可以覆盖前面定义的样式的意思。好绕嘴，真蛋疼。
